### PR TITLE
move file type handling to ftdetect and ftplugin

### PR DESCRIPTION
**Pull request by Konfekt**

### CODE REVIEW

**Comment by lucc** [comment]
Did you try that patch? I am using neovim and they have a filetype gpg already so your change breaks the functionality of the plugin. I send a PR to vim to change their filetype gpg to gpgconf so we can try to do your changes afterwards.

**Comment by Konfekt** [comment]
Ah, nope, did not try it out yet.

That's a good proposition. If not we could call our filetype gnupg instead.

**Comment by lucc** [comment]
We can also have a look at the way it is done for .gz files. They don't get a file type from the gz ending (which makes sense because it could be `script.sh.gz`). Maybe it doesn't even make sense to set the filetype to gpg (or any variant) as the file is much more likely to be of some other filetype internally.

**Comment by Konfekt** [comment]
True. That makes a lot of sense. Therefore this file type handling is superfluous. Instead, putting the autocmd's into a ftdetect/.. file is sufficient.

**Pull request closed without merging**
